Symfotweet\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    # fields:
    #     name:
    #         type: string
    #         length: 255
    #     password:
    #         type: string
    #         length: 255
    #     salt:
    #         type: string
    #         length: 255
    #     roles:
    #         type: array
