symfotweet_user:
    resource: "@SymfotweetUserBundle/Resources/config/routing.yml"
    prefix:   /

symfotweet_tweet:
    resource: "@SymfotweetTweetBundle/Resources/config/routing.yml"
    prefix:   /
